### ISSUE TITLE
We couldn't save your tab settings. Please try again.

### ISSUE THREAD

**Issue by adityap31** [OfficeDev/microsoft-teams-library-js#1171]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/2426723/167861872-6bbf4187-39a6-4d05-9936-ef2a1234f029.png">

We suddenly started getting this issue when we publish the local app.

**Comment by sayali-MSFT** [comment]
@adityap31 - Could you please share the sample or manifest.so that we can tried it from our end?

**Comment by sayali-MSFT** [comment]
@adityap31 -do you have any more owner in your team? If yes, please ask them to remove you and add as a member, try if you can add planner with member permission. once done, ask your team owner to provide you owner permission again.

**Comment by adityap31** [comment]
`{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
    "manifestVersion": "1.11",
    "version": "1.0.0",
    "id": "a536bcbc-b7e5-####-ba5c-#####",
    "packageName": "com.#####.msteams.#####",
    "developer": {
        "name": "##########",
        "websiteUrl": "https://www.##########.de/",
        "privacyUrl": "https://##########/datenschutzerklaerung/",
        "termsOfUseUrl": "https://##########/pdf/agb_idgard.pdf",
        "mpnId": "5460295"
    },
    "accentColor": "#009637",
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "showLoadingIndicator": false,
    "name": {
        "short": "##########-{{TEST_ENV}}",
        "full": "########## for Teams"
    },
    "description": {
        "short": "########## integration in MS Teams",
        "full": "########## integration in Microsoft Teams, for secure file upload and download, sharing, collaboration and chat"
    },
    "staticTabs": [],
    "configurableTabs": [
        {
            "configurationUrl": "https://{{PUBLIC_HOSTNAME}}/config/?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}&culture={locale}",
            "canUpdateConfiguration": true,
            "scopes": [
                "team"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "######.azurewebsites.net",
        "msteams.######.######.######"
    ],
    "localizationInfo": {
        "defaultLanguageTag": "en-us",
        "additionalLanguages": [
            {
                "languageTag": "de-de",
                "file": "de-DE.json"
            },
            {
                "languageTag": "fr-fr",
                "file": "fr-FR.json"
            }
        ]
    }
}`

**Comment by adityap31** [comment]
> @adityap31 -Do you have any more owner in your team? If yes, please ask them to remove you and add as a member, try if you can add planner with member permission. once done, ask your team owner to provide you owner permission again.

Thanks! Will ask the admins to follow the steps and confirm.

**Comment by adityap31** [comment]
@sayali-MSFT We still get the same issue.

**Comment by sayali-MSFT** [comment]
@adityap31 -Did you add validDomains in manifest file? If your tab configuration or content UI needs to navigate to any other domain besides the one use for tab configuration, that domain must be specified validDomain.
Do not include the domains of identity providers you want to support in your app.

**Comment by sayali-MSFT** [comment]
@adityap31 - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by crtjr64** [comment]
I'm not the original user but am having the same issue with a custom application. It worked fine in the personal tab and I have no idea how to set Valid Domain in the manifest file as I am using Developer Portal

**Comment by sayali-MSFT** [comment]
@crtjr64 - Open [Developer porta](https://dev.teams.microsoft.com/apps/14dd8b0f-b93b-49e6-be9a-4fa731ecdf36/domains)l->App->Create/Import App->Configure->Domain->Add a domain.
You can add like below-
![image](https://user-images.githubusercontent.com/93527375/178243013-c4a97acf-b109-4848-ab9b-e8061f51dc1d.png)

**Comment by crtjr64** [comment]
Sorry, I already figured it out and I'm still getting the message

**Comment by sayali-MSFT** [comment]
@crtjr64 -Could you please share the manifest json, So that we can try it from our end?

**Comment by sayali-MSFT** [comment]
@crtjr64 -Tracking issue here-https://github.com/MicrosoftDocs/msteams-docs/issues/6423
