### ISSUE TITLE
Microsoft Teams task modules can't be closed on IOS

### ISSUE THREAD

**Issue by Hensorskyy** [OfficeDev/microsoft-teams-library-js#1494]
We have upgraded the `@microsoft/teams-js` library to version 2.6.0 and experiencing an issue with closing task modules on IOS mobile devices. Neither `tasks.submitTask()` nor `dialog.submit()` closes the task modules. It was tested on  MS Teams version 4.22.1 (build 4.22.77.2022223502/1212). 
Both approaches work correctly on the web and desktop clients.

**Comment by ChetanSharma-msft** [comment]
Hello @Hensorskyy - This is a known issue.
We have raised a bug for it and informed engineering team.
We will let you know the updates once we have any.

**Comment by Hensorskyy** [comment]
Thanks, @ChetanSharma-msft!
Is there an ETA for a fix?

**Comment by ChetanSharma-msft** [comment]
Hello @Hensorskyy - Currently we don't have any exact ETA to share but engineering team is proactively working on it.

**Comment by LukasNespor** [comment]
Hi @ChetanSharma-msft,
any update? It's almost 2 months since last comment.

**Comment by ChetanSharma-msft** [comment]
Hello @LukasNespor - We will check the updates on this issue and let you know the updates soon.

**Comment by sayali-MSFT** [comment]
Hello @LukasNespor - Issue is resolved on latest build.
Could you please check it once?
IOS Teams Version-5.2.0(build- 5.2.77.2023023402/0205)
Teams JS Version-2.6.1

**Comment by LukasNespor** [comment]
@sayali-MSFT Hmm. I had to change all calls to ``dialog.submit()`` because from some reason submit function moved to ``dialog.url.submit()``. Same for ``dialog.open()`` > ``dialog.url.open()``. Unfortunately it is still not working on iOS.

iOS Teams app build: 5.2.77.2023023402/0205 (General)
@microsoft/teams-js 2.8.0

Btw. I didn't find any info about changing dialog namespace in the [changelog](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/CHANGELOG.md).

**Comment by sayali-MSFT** [comment]
@LukasNespor -We are trying it again teams JS Version-2.8.0 and get back to you.

**Comment by sayali-MSFT** [comment]
@LukasNespor - We are tested the task module function `dialog.url.submit()` and `dialog.url.open()` with @microsoft/teams-js 2.8.0.It is working fine from our end.
Could you please check it once the below teams and IOS version?

iOS Teams app build: 5.2.77.2023023901/0210 (General)
@microsoft/teams-js 2.8.0
IOS version - 16.3
