### ISSUE TITLE
Clipboard api throws 'NotAllowedError: Failed to execute 'write' on 'Clipboard': Document is not focused'

### ISSUE THREAD

**Issue by ZimnitskiYury** [OfficeDev/microsoft-teams-library-js#2196]
**Clipboard write() method not working in desktop Teams**

I'm developing a personal tab for Microsoft Teams. Part of the functionality of my app is copying some data to the clipboard. For this, I use the write() method from the clipboard namespace. **It works fine in the web version of Teams** but throws an error in the desktop Teams.
`Failed to copy to clipboard. NotAllowedError: Failed to execute 'write' on 'Clipboard': Document is not focused.`

Here is the code snippets that I use to copy data to the clipboard:
1.
```
const content = ‘Hello, world!’; 
const blob = new Blob([content], { type: ‘text/plain’ });
clipboard.write(blob).catch((error) => { throwError(error); });
```

2. I also tried to use window.focus() and this approach, but neither of them worked:
```
const content = ‘Hello, world!’;
const blob = new Blob([content], {type: ‘text/plain’});

const button = document.createElement(‘button’); 
button.innerHTML = ‘Copy’; 
button.style.display = ‘none’; 
button.addEventListener(‘click’, async () => { 
    clipboard.write(blob)
                   .catch((error) => { 
                       throwError(error); 
                   })
                  .finally(() => { 
                     button.remove(); 
                  });
}); 
document.body.append(button); 
pages.returnFocus(); 
button.focus(); 
button.click();
```

**Comment by Prasad-MSFT** [comment]
The PR #2201   is a WIP to fix this issue, so please follow that PR for tracking when the fix is available!

**Comment by ZimnitskiYury** [comment]
actual for #2220

**Comment by shrshindeMSFT** [comment]
Thank you for reporting. I'll look into it and see if I can repro this issue.

**Comment by shrshindeMSFT** [comment]
Thank you for your patience. The fix for this issue is deployed and is available for everyone to use.

**Comment by ZimnitskiYury** [comment]
@shrshindeMSFT issue still exist. 
microsoft/teams-js: 2.24.0
Microsoft Teams version: 24137.2216.2931.2440
The client version is 49/24050307617.

if i write to clipboard image:

- web teams works fine
- desktop throws error `Failed to copy to clipboard. NotAllowedError: Failed to execute 'write' on 'Clipboard': Document is not focused.`

if I write to clipboard text/plain or text/html:

- web and desktop teams throw Internal Error 
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/57269588/1906ef24-65b1-4275-8e2d-cb6df2ce864a)
