### ISSUE TITLE
MeetingId is never being populated.

### ISSUE THREAD

**Issue by unckleg** [OfficeDev/microsoft-teams-library-js#384]
- As the title says meetingId of teams context is never being populated. 
- Documentation is full of stuff that is "exposed" to devs, but in practice nothing is working,

**Comment by unckleg** [comment]
Referencing this also: #386

**Comment by VaraPrasad-MSFT** [comment]
@unckleg,  This issue is fixed and soon available in GA.

**Comment by GavinThompson** [comment]
@VaraPrasad-MSFT Do you have an ETA on when this will be available? Currently building a Tabs app, and context.meetingId is [available in the documentation](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest), however it is always returning a blank string.

**Comment by VaraPrasad-MSFT** [comment]
@GavinThompson , We don't have any ETA to share when it will be available in GA.

**Comment by GavinThompson** [comment]
@Gousia-MSFT @VaraPrasad-MSFT  This has been closed but the bug still appears to be present, was a fix released?

**Comment by VaraPrasad-MSFT** [comment]
@GavinThompson , We are tracking this internally but we can't give any ETA on this.
