### ISSUE TITLE
getAuthToken fails with "Definition not found" in desktop and mobile app

### ISSUE THREAD

**Issue by rolandbodenstaff** [OfficeDev/microsoft-teams-library-js#675]
microsoftTeams.authentication.getAuthToken returns an error message "Definition not found" in desktop and mobile app for most users(a few still work). In the browser everything works fine for all users. The app is run by clicking a message from our chatbot which opens a modal/popup in teams itself. We are running sdk version 1.10.0 and version 1.4.00.26376 of teams.

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into it I will get back to you soon.
We have got similar issue #654  where user was facing it on iOS, are you doing it on same?

**Comment by rolandbodenstaff** [comment]
No this is on Windows and all mobile devices for only the desktop app. The browser based app work fine. Small note we use SSO authentication.

**Comment by rolandbodenstaff** [comment]
I think it's the same issue as #617 it worked fine for a year or so. Only certain users on certain devices experience this. A colleague has the issue when he enabled Developer preview when he disabled it it works again.

**Comment by HunaidHanfee-MSFT** [comment]
We have a repro at our end. We are looking into this. I will get back to you with updates.

**Comment by HunaidHanfee-MSFT** [comment]
We have raised a bug. I will update you once it is fixed or if I got any updates.
Thanks

**Comment by rolandbodenstaff** [comment]
Any update or is there a workaround available?

**Comment by HunaidHanfee-MSFT** [comment]
The team is working on it. We got to know about the repro at our end is when opening the task module with deeplink. Could you please confirm if you are also facing this issue when doing same?

**Comment by rolandbodenstaff** [comment]
Correct we also open a popup window using a deeplink. In this popup window a website is loaded and we attempt to retrieve an accesstoken which used to work .

**Comment by rolandbodenstaff** [comment]
It has been over a month and there is no solution available. This is not a problem with the library itself probably but with an internal change of how teams work. Is there any way we can speed up this process?

**Comment by janandreschweiger** [comment]
This is really poor. Our customers are upset, because of all the errors: https://github.com/OfficeDev/microsoft-teams-library-js/issues/675#issuecomment-950188217

**Comment by nero-nazok** [comment]
Is there at least a timeline HunaidHanfee-MSFT? Sovling this issue is indeed of vital importance to our company.

**Comment by HunaidHanfee-MSFT** [comment]
@janandreschweiger - We are working on the issues shared by you via email. I will check and let you know the status.

**Comment by HunaidHanfee-MSFT** [comment]
@nero-nazok, Internal engineering team is working on it, I don't have a timeline to share but I will keep you posted here.

Thanks

**Comment by Ramizkhan313** [comment]
@HunaidHanfee-MSFT 
We are also getting **Auth library error** on **Microsoft teams mobile app** in microsoftTeams.authentication.getAuthToken() method for our custom app.

 Please find attached screenshot.

![code](https://user-images.githubusercontent.com/29159308/140550773-0e212431-4bc7-4cdc-8751-4b31f7f532d8.png)
![team error](https://user-images.githubusercontent.com/29159308/140550782-ba289eec-4c14-4b89-9381-984820cd69d8.png)

**Comment by florian-hammertaler** [comment]
@HunaidHanfee-MSFT @v-chetsh 

We receive tons of complaints on a daily basis, because of this issue. It's over a month now. This issue should be top priority, as it breaks many other popular Teams Apps too. When will you resolve this issue?

Is there another library or authentication option available?

**Comment by nero-nazok** [comment]
Short note: We experience this issue now in Chrome and all Desktop versions. Firefox is the only environment, where everything works as expected.

I totally agree with @florian-hammertaler. This issue should already have been resolved a long time ago.

**Comment by nils-tahler** [comment]
Same here. Our users are pretty upset. I have been working as a Slack developer for years and never experienced something like that.

**Comment by Ramizkhan313** [comment]
@HunaidHanfee-MSFT @v-chetsh @nils-tahler @nero-nazok @florian-hammertaler 

We are facing business loss due to this issue and irony is Microsoft don't care about it, they outsourced most of their works to vendor partners in India, and they dont understand the criticality of the issue, customers can't use our app. It is really frustrating, upsetting for the startup business like us.

**Comment by janandreschweiger** [comment]
Same here @Ramizkhan313. We are a major firm with hundreds of enterprise customers. Unfortunately, this is not acceptable any more.

**Comment by nils-tahler** [comment]
I have read your comment @janandreschweiger: https://github.com/OfficeDev/microsoft-teams-library-js/issues/690#issuecomment-965053195

Please have a look on it @HunaidHanfee-MSFT. We have the same setup and get the exact same issue.

**Comment by Wajeed-msft** [comment]
@Ramizkhan313 , @nils-tahler , @janandreschweiger -  I am checking this with engineering team for update. I'll post as soon as I have updates.

**Comment by nils-tahler** [comment]
Thank you @Wajeed-msft. Please resolve this issue soon!!

**Comment by rolandbodenstaff** [comment]
This is just unacceptable we created an Microsoft premium support ticket to which we get the response because it's a dev issue we need to click the link in de msftbot first post to escalate the issue which we did. Still no response... @Wajeed-msft how does it take 14 days to get an update? It has been a total of almost 2 months now our customers are not happy to say the least. Is there any way to get direct contact with the engineering team on this?

**Comment by lokimeyburg** [comment]
Hi @rolandbodenstaff, apologies for taking two weeks to get back to you. We have identified a fix but we are still testing all the scenarios before rolling it out. Keep in mind that once we have verified the fix in our canary build, it can still take a few weeks before it becomes generally available.

**Comment by HunaidHanfee-MSFT** [comment]
We have got 3 issue on this thread and updates on them are - 

1. Issue (Windows): The authentication/SSO raises the "_Definition not found_" error. - We have the repro that is already shared with internal team and team is testing fix internally. ETA isn't available for it, it can take few weeks before it becomes generally available.
2. , Issue (iOS): The authentication/SSO raises the "_Auth library error_" error. - We have the repro and team has identify a fix and testing it internally. It will also gonna take some weeks to be available.
3. Card buttons and links don't work any more in the compose box - We have the repro and bug is raised for it. Team is working on it.

**Comment by rolandbodenstaff** [comment]
It has been almost 4 weeks since the last update and still the same error message as 81 days ago. Is there any solution or even a test of the internal fix that I can do to get this working again?

**Comment by prabureddy** [comment]
It's been many days and no solution. It'll be good if you roll out a new version with this fix ASAP.
👀

**Comment by HunaidHanfee-MSFT** [comment]
We didn't get any updates from the internal engineering team. I will post as soon as we have some updates and let you know current status.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@janandreschweiger  - "_Auth library Error_" issue on iOS is resolved. @Joyeconnect, @vibhor-mungee - 
We have check and confirm that this issue is fixed and we are no longer seeing "_Auth library Error_" and we are able to get the access token. Could you please try and check if you are still able to reproduce this issue in the latest build?

Thanks

**Comment by rolandbodenstaff** [comment]
@HunaidHanfee-MSFT  what about the issue that this ticket start with "Definition not found"?

**Comment by HunaidHanfee-MSFT** [comment]
We are not having any updates from the internal engineering team. I will respond back as soon as I have anything on it.

**Comment by rolandbodenstaff** [comment]
It seems to work again on mobile only! Web and desktop which are the most important still don't work unfortunately.

**Comment by prabureddy** [comment]
Is there any way to get unblocked from this...

![mr-bean-mr](https://user-images.githubusercontent.com/44055337/148345196-fb6e62c6-dd83-47ce-9b03-504e54652d18.gif)

**Comment by HunaidHanfee-MSFT** [comment]
@prabureddy, @janandreschweiger,  @Joyeconnect, @vibhor-mungee   - 
We have tested opening Task module using task/fetch method and seen that issue is not there? Could you please confirm that this workaround works for you? About the actual bug we have posted again to engineering team. We will share as soon as we heard from them. 

Thanks

**Comment by rolandbodenstaff** [comment]
@HunaidHanfee-MSFT any updates? Is this normal for a bug to be introduced and be around for more than 3 months? What do I need to do give this more priority?

**Comment by HunaidHanfee-MSFT** [comment]
@rolandbodenstaff  - Bug is Priority one and engineering team is working on it. 

We have tested opening Task module using task/fetch method and seen that issue is not there? Could you please confirm that this workaround works for you?

**Comment by Nils-van-Schaik** [comment]
@HunaidHanfee-MSFT, I am a colleague of @rolandbodenstaff.
What exactly is the task/fetch workaround? If you mean using the appid from Teams admin center instead of the manifest appid, we have confirmed it works, but it is not a suitable workaround for us, since our bot is multitenant and the appid from admin center is different for each customer.
If you mean another workaround, can you please remind us again, because I seem to have missed it.

**Comment by HunaidHanfee-MSFT** [comment]
Hello @Nils-van-Schaik - 
I am talking about invoking the task module with the bot. So the workaround I am suggesting is, bot will send a card and using that card you can open task module/popup instead deeplink. You have to do as mention here - [link](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs#bot-framework-card-actions-vs-adaptive-card-actionsubmit-actions)

Have a look at this doc for more information --
[Use task modules from bot](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs)

**Comment by Nils-van-Schaik** [comment]
@HunaidHanfee-MSFT 
I have implemented the task/fetch workaround, but unfortunately I still get the "getAuthTokenForApp: Failed with error - Definition not found" error.

**Comment by TDE-Communardo** [comment]
Hi @HunaidHanfee-MSFT, 
we are facing the same issue while trying to open a task module using a deeplink: "Definition not found"...
We are also using the usual TeamsFX SSO solution for authentication.
Are there any updates on this issue ?

**Comment by Meghana-MSFT** [comment]
Team is looking into the fix, we do not have any ETA to share.

**Comment by janandreschweiger** [comment]
How is it even possible that a company like Microsoft doesn't manage to fix such a serious error after several months?

**Comment by nero-nazok** [comment]
@Meghana-MSFT @v-chetsh 

We had a big team meeting today. If this error is not fixed in the next 2 weeks or there is a workaround, we will dissolve our teams app and focus completely on Slack. The support is in no way acceptable.

**Comment by florian-hammertaler** [comment]
@nero-nazok I have very good contacts with Microsoft Dublin. Two weeks is a good time horizon. If nothing has happened by then, I will complain to management about those responsible.

**Comment by nils-tahler** [comment]
It really is time to file a complaint. Otherwise, nothing will change in the next two months. We have lost customers due to your lack of support.

**Comment by rolandbodenstaff** [comment]
@florian-hammertaler please do file a complaint. It has almost been 5 months now with constants checking with the engineering team which either doesn't seem to happen or are not capable to fix the issue because the problem is somewhere else. @Meghana-MSFT where can we file a complaint?

**Comment by v-chetsh** [comment]
Hello Everyone,
Engineering team has fixed this issue but it is not publicly rolled out as of now.
We do not have ETA to share but will update you once it will roll out publicly.

**Comment by janandreschweiger** [comment]
Thank you @v-chetsh. Finally some good news!

**Comment by Nils-van-Schaik** [comment]
Yes, another 3 weeks have passed since the last update. When is this going to be released?

**Comment by Meghana-MSFT** [comment]
We got an update that the fix is available publicly now. We are also testing the fix internally.

**Comment by Nils-van-Schaik** [comment]
Nothing's changed on our end. Running Teams client version 1.5.00.5967 (64-bit).

**Comment by Meghana-MSFT** [comment]
We got the below update from the engineering team saying -
"Partners need to use the internal app ID in deep links to task modules rather than the external ID from their manifest. This applies to sideloaded and LOB apps. If they open a task module using a deep link with the external ID then getAuthToken and other APIs that depend on the app definition will not work. We have no plans to change this because it would introduce serious security issues into the product."

**Comment by Nils-van-Schaik** [comment]
So we are back to the work-around of October 26th that does not really work for multi-tenant bots?
If it's a security problem, how come this is working on Android? Are you saying the Teams app on Android is unsafe?

**Comment by Meghana-MSFT** [comment]
We have raised a bug for this issue on Android. Team will look into it.

**Comment by rykowski-rykowski** [comment]
I dig in in MS code.. and no chance to work! MS do a simple comparison: 
![image](https://user-images.githubusercontent.com/43166323/168596552-d59549cb-1894-4b67-abd8-afc22adfb4c4.png)
appdefinition.id = this i randomly (per tenant) generated app id that can be found in teams admin center as APP ID
t = this is app id that comes from deeplink, we put in deeplink id from manifest.json, but it occurs in teams admin center as EXTERNAL APP ID. 

So there is no way that i will work in desktop app and web browser.

**Comment by ydogandjiev** [comment]
@rykowski-rykowski, this behavior is by design. Relaxing the app ID check you have highlighted would allow a sideloaded or line of business app to impersonate one of our first party full trust applications which would in turn give it access to tokens for every single resources that the Teams Client(s) are pre-authorized for (including Graph, Substrate, SharePoint, etc.).

Have you considered looking up your app's generated app ID via our Graph APIs and using it to create the deep link(s):
https://docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&tabs=http#example-3-find-application-based-on-the-teams-app-manifest-id

**Comment by abdulkareemnalband** [comment]
how stable is internal id?
is it same for all users in organization?
is it same for app installed in team scope vs personal scope?
does it differs between different organizations for same app?

**Comment by rykowski-rykowski** [comment]
> @rykowski-rykowski, this behavior is by design. Relaxing the app ID check you have highlighted would allow a sideloaded or line of business app to impersonate one of our first party full trust applications which would in turn give it access to tokens for every single resources that the Teams Client(s) are pre-authorized for (including Graph, Substrate, SharePoint, etc.).
> 
> Have you considered looking up your app's generated app ID via our Graph APIs and using it to create the deep link(s): https://docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&tabs=http#example-3-find-application-based-on-the-teams-app-manifest-id

Got it. Thank you for explanation. 

Graph call is one of the option. But we try to avoid graph call, especially that it requires as i remember: AppCatalog.Read.All, AppCatalog.ReadWrite.All. It will make "doable" but IT Admins will scared :) if the app will be able to get '.All' something.

And just want to clarify. We we develop ms teams app that will be available on ms teams store. We can say that it will be on PROD only with one app id (like Polly), but on developement/test/qa/other stages when we upload apps manually to/through teams admin center it has got two ids (app id and external app id). So I would say it really make it difficult to prepare mutlitenant apps. We simulate testing by upolading app - on same time  - to 2 or 3 different tenants.

**Comment by ChetanSharma-msft** [comment]
@rykowski-rykowski - Hope  you are doing well !!
Please let us know if you need any help or shall we close this issue?

**Comment by ydogandjiev** [comment]
@abdulkareemnalband:

**How stable is internal id?**
The internal ID will not change unless the tenant admin completely removes the app from the LOB/organization catalog and then re-adds it again (at which point a new internal ID will get generated). If admins just update the app in-place by uploading a new package the internal ID is preserved.

**Is it same for all users in organization?**
Yes, the internal app ID is the same for all users in the organization.

**Is it same for app installed in team scope vs personal scope?**
Yes, the internal app ID is the same for all scopes where the app appears.

**Does it differs between different organizations for same app?**
Yes, it does. Each organization where the app is deployed will have its own unique internal ID for the application. The only way to get a stable and globally unique ID for your app is by distributing it via the Teams store:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish
